### ISSUE TITLE
[feature suggestion] force-safely

### ISSUE THREAD

**Issue by guicho271828** [dsorokin/trivial-lazy#1]
I like the way trivial-lazy is written and provides only the trivial/core features.
So I'm currently writing a utility wrapper on it, [eazylazy](https://github.com/guicho271828/eazylazy), which I recently separated from my private utility library. I extensively use it in my research.

However, I noticed there are some inconvenience. Since common-lisp is basically a strict evaluation language, the user of trivial-lazy may (accidentally or intentionally) mix thunks and real objects at the same time, e.g. in the same structure, list, sequences. 

Essentially, I suggest a safe version of `force`.

```cl
(defun force-safely (thunk?)
  (if (functionp thunk?)
      (funcall thunk?)
      thunk?))
```

And also a compiler-macro that converts `force-safely` into plain `force`.
(Another option is always using the safe version of `force` normally and declare it `inline`. If the thunk is declared to be of type `function` in the caller's environment then the `if` statement will be safely removed by the compiler.)

**Comment by dsorokin** [comment]
Hi Masataro,

Sorry for too long delay. I completely forgot about your request because of my job and other events in my life… I’ve just added the function as you offered. Here I prefer a function to macro. 

Thanks, David
